// Auto-generated by repack.py. Do not edit by hand — re-runs will overwrite.
const VERSION = '7ebe878';
const CACHE = `taiwan-crop-${VERSION}`;
const PRECACHE = ["index.html", "assets/page-data.json", "toolbox.html", "crop-dashboard.html", "myfarm.html", "toolbox-shared.js", "toolbox-entry.js", "toolbox-product-calcs.js", "toolbox-assets/crop-params.json", "toolbox-assets/crop_chars.json", "assets/60c9445d-64d5-4600-8fc2-be7e2da47944.js", "assets/f740b2a9-f5f5-436f-9ee2-5c88da1a82a5.js", "assets/full_page.avif", "assets/tomato_dashboard.avif", "assets/taoyuan_detail.avif"];

self.addEventListener('install', e => {
  // Take over immediately on first install so cache is populated without a reload.
  self.skipWaiting();
  e.waitUntil(
    caches.open(CACHE).then(c =>
      // Best-effort: don't fail install if one URL 404s.
      Promise.all(PRECACHE.map(u =>
        c.add(new Request(u, { cache: 'reload' })).catch(err =>
          console.warn('[sw] precache miss', u, err))
      ))
    )
  );
});

self.addEventListener('activate', e => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)));
    await self.clients.claim();
  })());
});

const _SCOPE_PATH = new URL(self.registration.scope).pathname;

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  // Only manage same-origin requests. Live nongzhidao / weather API stay
  // direct so they always get the freshest data and never hit a stale cache.
  if (url.origin !== self.location.origin) return;
  // 只管自己站台路徑（GH Pages 上 nongzhidao 資料站與本站同網域——
  // 不加這條會被 SWR 蓋到，行情變成「上一次的」才對外顯示）
  if (!url.pathname.startsWith(_SCOPE_PATH)) return;
  const isHTML =
    req.destination === 'document' ||
    url.pathname.endsWith('/') ||
    url.pathname.endsWith('.html');

  // HTML 與工具箱檔案（非 /assets/）→ stale-while-revalidate：
  // 有快取立刻回（秒開），同時背景抓新版更新快取（下次就是新的）。
  // 新 deploy 會換 SW 版本號 → 全新 cache + install 重新預抓，不會卡舊版。
  if (isHTML || !url.pathname.includes('/assets/')) {
    // HTML 頁面帶 ?crop= 等查詢參數但內容同一份 → 用純路徑當快取鍵，
    // 才吃得到 install 時預抓的 toolbox.html / crop-dashboard.html。
    const key = isHTML ? new Request(url.origin + url.pathname) : req;
    e.respondWith((async () => {
      const cached = await caches.match(key, { ignoreSearch: isHTML });
      // no-cache: 背景更新一定去伺服器驗證，不吃瀏覽器 HTTP 快取的舊檔
      const refresh = fetch(req.url, { cache: 'no-cache' }).then(res => {
        if (res && res.ok) {
          const copy = res.clone();
          caches.open(CACHE).then(c => c.put(key, copy));
        }
        return res;
      }).catch(() => null);
      if (cached) return cached;          // 秒開；refresh 在背景跑
      const res = await refresh;          // 冷載入：等網路
      if (res) return res;
      throw new Error('offline + no cache');
    })());
    return;
  }

  // 重資產（/assets/ 的 avif/woff2/js bundle）: cache-first。The cache name
  // includes VERSION, so a new deploy gets a fresh cache and old entries are
  // dropped in activate().
  e.respondWith((async () => {
    const cached = await caches.match(req);
    if (cached) return cached;
    const res = await fetch(req);
    if (res.ok) {
      const copy = res.clone();
      caches.open(CACHE).then(c => c.put(req, copy));
    }
    return res;
  })());
});
