// Auto-generated by repack.py. Do not edit by hand — re-runs will overwrite.
const VERSION = '6cceb1b';
const CACHE = `taiwan-crop-${VERSION}`;
const PRECACHE = ["index.html", "assets/page-data.json", "assets/60c9445d-64d5-4600-8fc2-be7e2da47944.js", "assets/f740b2a9-f5f5-436f-9ee2-5c88da1a82a5.js", "assets/full_page.avif", "assets/tomato_dashboard.avif", "assets/taoyuan_detail.avif"];

self.addEventListener('install', e => {
  // Take over immediately on first install so cache is populated without a reload.
  self.skipWaiting();
  e.waitUntil(
    caches.open(CACHE).then(c =>
      // Best-effort: don't fail install if one URL 404s.
      Promise.all(PRECACHE.map(u =>
        c.add(new Request(u, { cache: 'reload' })).catch(err =>
          console.warn('[sw] precache miss', u, err))
      ))
    )
  );
});

self.addEventListener('activate', e => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  // Only manage same-origin requests. Live nongzhidao / weather API stay
  // direct so they always get the freshest data and never hit a stale cache.
  if (url.origin !== self.location.origin) return;
  const isHTML =
    req.destination === 'document' ||
    url.pathname.endsWith('/') ||
    url.pathname.endsWith('.html');

  if (isHTML) {
    // Network-first: every reload pulls the latest HTML (which references the
    // latest hashed asset URLs), cache only as offline fallback.
    e.respondWith((async () => {
      try {
        const res = await fetch(req);
        const copy = res.clone();
        caches.open(CACHE).then(c => c.put(req, copy));
        return res;
      } catch {
        const cached = await caches.match(req);
        if (cached) return cached;
        throw new Error('offline + no cached HTML');
      }
    })());
    return;
  }

  // 工具箱資料與腳本（非 /assets/ 的一般檔案）更新頻繁 → network-first，
  // 快取只當離線備援。這樣推新資料（crop-params 等）不必等 SW 版本號。
  if (!url.pathname.includes('/assets/')) {
    e.respondWith((async () => {
      try {
        const res = await fetch(req);
        if (res.ok) { const copy = res.clone(); caches.open(CACHE).then(c => c.put(req, copy)); }
        return res;
      } catch {
        const cached = await caches.match(req);
        if (cached) return cached;
        throw new Error('offline + no cache');
      }
    })());
    return;
  }

  // 重資產（/assets/ 的 avif/woff2/js bundle）: cache-first。The cache name
  // includes VERSION, so a new deploy gets a fresh cache and old entries are
  // dropped in activate().
  e.respondWith((async () => {
    const cached = await caches.match(req);
    if (cached) return cached;
    const res = await fetch(req);
    if (res.ok) {
      const copy = res.clone();
      caches.open(CACHE).then(c => c.put(req, copy));
    }
    return res;
  })());
});
